### ISSUE TITLE
Remove-ClientTorrent без удаления файлов

### ISSUE THREAD

**Issue by Another-1** [Another-1/RT_backuper#3]
Хорошо бы добавить в Remove-ClientTorrent параметр удаления файлов. Сейчас там хардкодно deleteFiles = $true

**Comment by NeBioNik** [comment]
Казалось бы у нас есть две концепции.
1. Скачать - хранить - не удалять раздачи.
2. Скачать - забекапить - удалить раздачу.

В какую из них вписывается необходимость удалить раздачу, но оставить файлы?

**Comment by Another-1** [comment]
Для миграции раздач между клиентами без удаления файлов.

**Comment by NeBioNik** [comment]
Добавлено ` Remove-ClientTorrent ( [int]$torrent_id, [string]$torrent_hash, [switch]$deleteFiles ) {}`
Вызывать как флаг, т.е. `Remove-ClientTorrent 6231839 '40df22cbde2d3bab9ad74a9dc36eff570ff5f55d' -deleteFiles` - удалит файлы
`Remove-ClientTorrent 6231839 '40df22cbde2d3bab9ad74a9dc36eff570ff5f55d'` удалит только раздачу
